<a href="https://colab.research.google.com/github/shatabdabasu/Feature-Eng/blob/main/Ordinal_encoding_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/datasets/customer.csv')
df.sample(3)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

    age  gender   review education purchased
37   94    Male  Average        PG       Yes
28   48    Male     Poor    School        No
3    72  Female     Good        PG        No

In [24]:
df.sample(3)

    age gender review education purchased
43   27   Male   Poor        PG        No
6    18   Male   Good    School        No
40   39   Male   Good    School        No

In [25]:
df = df.iloc[:, 2:]

In [26]:
df.sample(2)

   review education purchased
40   Good    School        No
22   Poor        PG       Yes

In [27]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [28]:
X_train

     review education
37  Average        PG
9      Good        UG
19     Poor        PG
35     Poor    School
41     Good        PG
6      Good    School
8   Average        UG
30  Average        UG
21  Average        PG
25     Good    School
33     Good        PG
12     Poor    School
23     Good    School
34  Average    School
45     Poor        PG
27     Poor        PG
3      Good        PG
49     Good        UG
4   Average        UG
46     Poor        PG
11     Good        UG
38     Good    School
44  Average        UG
47     Good        PG
39     Poor        PG
16     Poor        UG
5   Average    School
17     Poor        UG
18     Good    School
42     Good        PG
43     Poor        PG
14     Poor        PG
7      Poor    School
22     Poor        PG
1      Poor        UG
0   Average    School
24  Average        PG
40     Good    School
20  Average    School
32  Average        UG

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG", "PG"]])

In [31]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [32]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [36]:
X_train

array([[1., 2.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.]])

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [39]:
le.classes_

array(['No', 'Yes'], dtype=object)